//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.08.04 at 01:45:55 PM MSK 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.kim.ru/soap/", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package ru.kim.soap;
